[package]
name = "hashmap_from_scratch"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
smallvec = "2.0.0-alpha.9"

[dev-dependencies]
rand = "0.8.5"
criterion = { version = "0.5", features = ["html_reports"] }


[[bench]]
name = "bench"
harness = false
